 platform:
   - x64
 
 configuration:
   - Debug

 image:
   - Visual Studio 2019
 
 environment:
   AWS_ACCESS_KEY_ID:
     secure: GIQzwkV21ZqWhzZ0ii13r4dOEZ6Pkq8r6Jajx18uEaY=
   AWS_SECRET_ACCESS_KEY:
     secure: 7sxn6236C/oltJYJfel3ISUxQfuBfB44QqdWs0Thjy+U3s+6MPugW8CGVlC8p0o8
 
   matrix:
    - nodejs_version: 11
      platform: x64
    - nodejs_version: 12
      platform: x64
    - nodejs_version: 13
      platform: x64
  
 install:
   - scripts\build-appveyor.bat
   - ps: if($env:appveyor_repo_tag -eq 'True') { npm run publish } else { echo "Not publishing binary because this is not a tag build" }
 
 build: OFF
 test: OFF
 deploy: OFF